#ifndef SET_TEST_H
#define SET_TEST_H
void test1_set_create();
void test2_set_create();
void test1_set_add();
void test2_set_add();
void test1_set_del();
void test2_set_del();
void test1_set_find();
void test2_set_find();
void test1_set_get_id();
void test2_set_get_id();
void test1_set_get_numberid();
void test2_set_get_numberid();
void test1_set_get_ids();
void test2_set_get_ids();
void test1_set_destroy();
void test2_set_destroy();
#endif